---
title: "exercise10"
format: html
editor: visual
---

# Exercise 10, Practice ANOVA

## Set up: Libraries and Data Wrangling

```{r}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(infer)
library(skimr)
#Still using bird data
f <- "https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/AVONETdataset1.csv"
d <- read_csv(f, col_names = TRUE)

d <- d |>
  select(Species1, Family1, Order1, Beak.Length_Culmen, Beak.Width, Beak.Depth, 
         Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level, 
         Trophic.Niche, Min.Latitude, Max.Latitude, Centroid.Latitude, Primary.Lifestyle, Range.Size) |>
  mutate(Migration = as.factor(Migration)) |>
  mutate(Beak.Length_CulmenLog = log(Beak.Length_Culmen), Tarsus.LengthLog = log(Tarsus.Length))
```

## Challenge 1

### Step 1

```{r}
#trophic level in relation to log(Mass)
tlM <- ggplot(data = d |> drop_na(Trophic.Level), aes(x = Trophic.Level, y = log(Mass))) +
  geom_boxplot() +
  geom_jitter() +
  ggtitle("log(Mass) and Trophic Level")

#Migration (as factor) in relation to log(Mass)
mm <- ggplot(data = d |> drop_na(Migration), aes(x = Migration, y = log(Mass))) +
  geom_boxplot() +
  geom_jitter() +
  ggtitle("log(Mass) and Migration")

plot_grid(tlM, mm)
```

### Step 2

```{r}
#Mass and trophic level model
m1 <- lm(log(Mass) ~ Trophic.Level, data = d)
#Madd and Migration model
m2 <- lm(log(Mass) ~ Migration, data = d)
```

### Step 3

```{r}
m2aov <- aov(log(Mass) ~ Migration, data = d)
posthoc <- TukeyHSD(m2aov, which = "Migration", conf.level = 0.95)
```

### Step 4

```{r}
#Origin F stat
original.F <- aov(aov(log(Mass) ~ Trophic.Level, data = df)) |>
  broom::tidy()|>
  filter(term == "Trophic.Level")
original.F

#Permutation distribution using {infer}
d <- d |> mutate(logMass = log(Mass))
permuted.F <- d |>
  specify(logMass ~ Trophic.Level) |>
  hypothesize(null = "independence") |>
  generate(reps = 1000, type = "permute") |>
  calculate(stat = "F")
visualize(permuted.F) +
  shade_p_value(obs_stat = original.F$statistic, direction = "greater")
p.value <- permuted.F |>
  get_p_value(obs_stat = original.F$statistic, direction = "greater")

```

## Challenge 2

### Step 1

```{r}
m3 <- lm(Beak.Length_CulmenLog ~ log(Mass), data = d)
m4 <- lm(Tarsus.LengthLog ~ log(Mass), data = d)
d <- d |>
  mutate(blcRes = m3$residuals, tlRes = m4$residuals)
```

### Step 2

```{r}
a <- ggplot(data = d, mapping = aes(x = Primary.Lifestyle, y = tlRes)) +
  geom_boxplot() +
  ggtitle("log(Tarsus Length) Residules and Primary Lifestyle")

b <- ggplot(data = d, mapping = aes(x = Trophic.Niche, y = blcRes)) +
  geom_boxplot() +
  ggtitle("log(Beak Length Culmen) Residules and Trophic Niche")

plot_grid(a, b)
```

### Step 3

```{r}
d <- d |>
  drop_na(Migration) |>
  mutate(logRange = log(Range.Size))
rangM1 <- lm(logRange ~ Migration, data = d)
summary(rangM)

#Releveling to see whats different
d$Migration <- relevel(d$Migration, ref = 2)
rangM2 <- lm(logRange ~ Migration, data = d)
summary(rangM2)

d$Migration <- relevel(d$Migration, ref = 3)
rangM3 <- lm(logRange ~ Migration, data = d)
summary(rangM3)

#Relevel back to og
d$Migration <- relevel(d$Migration, ref = 1)
#Tukey HSD
rangM_aov <- aov(logRange ~ Migration, data = d)
rangeM_THSD <- TukeyHSD(rangM_aov, which = "Migration", conf.level = 0.95)
```

### Step 4

```{r}
dp <- d |>
  filter(Order1 == "Passeriformes")
Paov1 <- aov(blcRes ~ Primary.Lifestyle, data = dp)
Paov2 <- aov(blcRes ~ Trophic.Level, data = dp)
p1 <- ggplot(data = dp, mapping = aes(x = Primary.Lifestyle, y = blcRes)) +
  geom_boxplot() +
  ggtitle("Rel Beak Length:Primary Lifestyle")
p2 <- ggplot(data = dp, mapping = aes(x = Trophic.Level, y = blcRes)) +
  geom_boxplot() +
  ggtitle("Rel Beak Length:Trophic Level")
plot_grid(p1, p2)

dp <- dp |>
  mutate(PL.TL = paste(Primary.Lifestyle, Trophic.Level))
p3 <- ggplot(data = dp, mapping = aes(x = PL.TL, y = blcRes)) +
  geom_boxplot() +
  ggtitle("Rel Beak Length: Lifestyle & Trophic Level")

Plm1 <- lm(blcRes ~ Primary.Lifestyle, data = dp)
summary(Plm1)
Plm2 <- lm(blcRes ~ Trophic.Level, data = dp)
summary(Plm2)
```

### Step 5

```{r}
P2wayaov <- aov(data = dp, blcRes ~ Primary.Lifestyle + Trophic.Level)
summary(P2wayaov)
```

### Step 6

```{r}
PaovInteraction <- aov(data = dp, 
                       blcRes ~ Primary.Lifestyle + Trophic.Level + Primary.Lifestyle:Trophic.Level)
summary(PaovInteraction)
```

### Step 7

```{r}
interaction.plot(x.factor= dp$Primary.Lifestyle, xlab = "Primary Lifestyle", trace.factor = dp$Trophic.Level,
                 trace.label = "Trophic Level", fun = base::mean, response = dp$blcRes, ylab = "Relative Beak Length")
```

### Step 8

```{r}

```
